swagger: '2.0'
info:
  title: 'Login API'
  description: 'Endpoint to authenticate a user.'
  version: '1.0'
paths:
  /api/v1/auth/login:
    post:
      tags:
        - 'Authentication'
      summary: 'Authenticate user'
      description: 'Authenticate a user with the provided credentials.'
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            type: 'object'
            properties:
              username:
                type: 'string'
              password:
                type: 'string'
      responses:
        200:
          description: 'User authenticated successfully'
          schema:
            type: 'object'
            properties:
              user:
                type: 'object'
                properties:
                  refresh:
                    type: 'string'
                  access:
                    type: 'string'
                  username:
                    type: 'string'
                  email:
                    type: 'string'
                  role:
                    type: 'string'
        401:
          description: 'Unauthorized - Wrong credentials'
