swagger: "2.0"
info:
  title: "User Registration"
  description: "API for registering a new user account."
  version: "1.0.0"
basePath: "/api/v1"
tags:
  - name: "Authentication"
paths:
  /auth/register:
    post:
      tags:
        - "Authentication"
      summary: "Register a new user account"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User registration details"
          required: true
          schema:
            type: "object"
            required:
              - "username"
              - "email"
              - "role"
              - "password"
            properties:
              username:
                type: "string"
                example: "example_user"
              email:
                type: "string"
                format: "email"
                example: "user@example.com"
              role:
                type: "string"
                example: "sadmin"
              password:
                type: "string"
                format: "password"
                example: "password123"
      responses:
        201:
          description: "Successfully created a new user account"
        400:
          description: "Failed to register due to bad request data"
        409:
          description: "Conflict - Email or username already taken"
